Update to ns 3.48 (#3)
* Update to ns-3.48

* Update readme

* Update instructions readme

* Update citation

diff --git a/utils/tests/gitlab-ci-code-linting.yml b/utils/tests/gitlab-ci-code-linting.yml
--- a/utils/tests/gitlab-ci-code-linting.yml
+++ b/utils/tests/gitlab-ci-code-linting.yml
@@ -2,112 +2,138 @@
 #
 # Contains jobs to check the ns-3 coding style and perform lint checking.
 
+# Common settings
+.code-linting-base:
+  stage: .pre
+  timeout: 1h
+  interruptible: true
+
 # Clang-format
-check-style-clang-format:
-  stage: code-linting
-  image: ubuntu:latest
+.check-style-clang-format:
+  extends: .code-linting-base
+  image: ubuntu:rolling
   before_script:
     - apt update
     - DEBIAN_FRONTEND=noninteractive apt install -y
       python3
-      clang-format-14
+      clang-format-$CLANG_FORMAT_VERSION
   script:
-    - python3 utils/check-style-clang-format.py .
-  timeout: 1h
+    - python3 utils/check-style-clang-format.py --verbose .
+
+check-style-clang-format-20:
+  extends: .check-style-clang-format
+  variables:
+    CLANG_FORMAT_VERSION: 20
+
+# check-style-clang-format-21:
+#   extends: .check-style-clang-format
+#   variables:
+#     CLANG_FORMAT_VERSION: 21
 
 # Clang-tidy
-.base-clang-tidy:
+clang-tidy-22:
+  extends: .code-linting-base
   stage: code-linting
-  image: ubuntu:latest
+  image: ubuntu:rolling
   variables:
     MPI_CI: 1
+    CLANG_TIDY_VERSION: 22
     CLANG_TIDY_OUTPUT: clang-tidy-output.log
+    FILES_CHANGED: git-diff-name-only.log
   before_script:
     - apt update
     - DEBIAN_FRONTEND=noninteractive apt install -y
-      clang cmake
-      clang-tidy clang-tidy-14
-      python3 python3-pip
+      clang-tidy-$CLANG_TIDY_VERSION clang-$CLANG_TIDY_VERSION cmake libstdc++-16-dev
       libboost-all-dev libeigen3-dev libgtk-3-dev libopenmpi-dev libsqlite3-dev
-      gsl-bin libgsl-dev libgsl27
+      gsl-bin libgsl-dev libgsl28
       git ssh
-    - pip3 install cppyy
-    - ./ns3 configure -d debug
+    - CXX=clang++-$CLANG_TIDY_VERSION ./ns3 configure -d debug
       --enable-clang-tidy
       --enable-examples --enable-tests --enable-asserts
-      --enable-mpi --enable-python-bindings
+      --enable-mpi
+  script:
+    - if (git remote | grep -qw upstream) ; then
+      git remote remove upstream ;
+      fi
+    - git remote add -t $CI_DEFAULT_BRANCH --no-tags -f upstream https://gitlab.com/nsnam/ns-3-dev.git
+    - git diff --name-only upstream/$CI_DEFAULT_BRANCH > $FILES_CHANGED
+
+    # Run clang-tidy on all files in the following cases: 1) default branch, 2) ".clang-tidy" file changed
+    # Otherwise, run clang-tidy on changed files only.
+    - |
+      if [[ $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH ]] ||
+         (grep -q ".clang-tidy" $FILES_CHANGED) ||
+         (grep -q "gitlab-ci-code-linting.yml" $FILES_CHANGED) ;
+      then
+        FILES_TO_CHECK="";
+        echo "Running clang-tidy on all files";
+      else
+        FILES_TO_CHECK=$(cat $FILES_CHANGED);
+        echo "Running clang-tidy on the following changed files:";
+        echo $FILES_TO_CHECK;
+      fi
+    - run-clang-tidy-$CLANG_TIDY_VERSION -p cmake-cache/ -quiet $FILES_TO_CHECK > $CLANG_TIDY_OUTPUT
+
+    # Check job results
+    - (! egrep -v "file not found \[clang-diagnostic-error\]" $CLANG_TIDY_OUTPUT | egrep -A3 "error:|warning:|note:")
+    - echo "No clang-tidy errors found"
+  dependencies: []
   artifacts:
     paths:
       - $CLANG_TIDY_OUTPUT
     when: on_failure
   timeout: 3h
 
-clang-tidy:
-  extends: .base-clang-tidy
-  rules:
-    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
-      when: never
-    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
-      when: on_success
-    - changes:
-        paths:
-          - .clang-tidy
-        compare_to: master
-      when: on_success
-  script:
-    - run-clang-tidy-14 -p cmake-cache/ -quiet
-      1> $CLANG_TIDY_OUTPUT
-      2> /dev/null
-    - (! egrep -A 3 "error:|warning:|note:" $CLANG_TIDY_OUTPUT)
-    - echo "No clang-tidy errors found"
-
-clang-tidy-diff:
-  extends: .base-clang-tidy
-  rules:
-    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
-      when: never
-    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
-      when: never
-    - changes:
-        paths:
-          - .clang-tidy
-        compare_to: master
-      when: never
-    - when: on_success
-  script:
-    - git remote add upstream https://gitlab.com/nsnam/ns-3-dev.git
-    - git fetch upstream master
-    # File paths generated by git diff are relative to the working tree. Therefore, iregex should only contain paths relative to the working tree.
-    - git diff -U0 upstream/master |
-      clang-tidy-diff-14.py -path cmake-cache/ -p1 -quiet -use-color
-      -iregex "(contrib|examples|src|scratch|utils)\/.+\.(cpp|cc|cxx|c|h|hpp)"
-      1> $CLANG_TIDY_OUTPUT
-      2> /dev/null
-    - if egrep -A 3 "file not found \[clang-diagnostic-error\]" $CLANG_TIDY_OUTPUT ; then
-      echo "Clang-tidy could not find the above files. Running a full clang-tidy check." ;
-      run-clang-tidy-14 -p cmake-cache/ -quiet
-      1> $CLANG_TIDY_OUTPUT
-      2> /dev/null ;
-      fi
-    - (! egrep -A 3 "error:|warning:|note:" $CLANG_TIDY_OUTPUT)
-    - echo "No clang-tidy errors found"
-
-# Emacs line
-emacs-line:
-  stage: code-linting
-  image: ubuntu:latest
-  script:
-    - (! grep -rn --include="*.h" --include="*.cc" "c-file-style:\"gnu\"" ) ||
-      (echo "Found Emacs lines on the above C++ files" && exit 1)
-    - echo "No Emacs lines found on C++ files"
-  timeout: 1h
-
 # Spell checking
 spell-check:
-  stage: code-linting
+  extends: .code-linting-base
   image: python:latest
   before_script:
     - pip install codespell
   script:
-    - codespell ./
-  timeout: 1h
+    # Get commit messages
+    - if (git remote | grep -qw upstream) ; then
+      git remote remove upstream ;
+      fi
+    - git remote add -t $CI_DEFAULT_BRANCH --no-tags -f upstream https://gitlab.com/nsnam/ns-3-dev.git
+
+    - git log --pretty=%B HEAD...upstream/$CI_DEFAULT_BRANCH ^upstream/$CI_DEFAULT_BRANCH > git_messages.txt
+    # Check source code and commit messages
+    - codespell -f -C0 ./
+
+# Check cmake format
+cmake-format:
+  extends: .code-linting-base
+  image: python:3.12
+  before_script:
+    - pip install pyyaml cmake cmake-format ninja
+  script:
+    - ./ns3 configure --enable-modules=core
+    - |
+      if (! ./ns3 build cmake-format-check) ; then
+        echo "Bad formatting detected in CMake files.";
+        echo "To fix the formatting issues, run the following command:";
+        echo "   $ ./ns3 build cmake-format";
+        echo "Note that it requires having cmake-format installed in your system.";
+        echo "You might need to run \"./ns3 configure\" after installing it.";
+        exit 1;
+      fi
+
+# Check Python format
+python-format-latest:
+  extends: .code-linting-base
+  image: python:latest
+  before_script:
+    - pip install black isort
+  script:
+    - black --check .
+    - isort --check .
+
+# Markdown lint
+markdown-lint:
+  extends: .code-linting-base
+  image: node:slim
+  before_script:
+    - npm install -g markdownlint-cli
+  script:
+    - markdownlint .
